<?php
return [
    // 'actionscheduler_actions',
    // 'actionscheduler_claims',
    // 'actionscheduler_groups',
    // 'actionscheduler_logs',
    'woocommerce_api_keys',
    'woocommerce_attribute_taxonomies',
    'woocommerce_downloadable_product_permissions',
    'woocommerce_log',
    'woocommerce_order_items',
    'woocommerce_order_itemmeta',
    'woocommerce_payment_tokenmeta',
    'woocommerce_payment_tokens',
    'woocommerce_sessions',
    'woocommerce_shipping_zones',
    'woocommerce_shipping_zone_locations',
    'woocommerce_shipping_zone_methods',
    'woocommerce_tax_rates',
    'wc_tax_rate_classes',
    'woocommerce_tax_rate_locations',
    'wc_admin_notes',
    'wc_admin_note_actions',
    'wc_category_lookup',
    'wc_customer_lookup',
    'wc_download_log',
    'wc_order_coupon_lookup',
    'wc_order_product_lookup',
    'wc_order_stats',
    'wc_order_tax_lookup',
    'wc_product_attributes_lookup',
    'wc_product_meta_lookup',
    'wc_rate_limits',
    'wc_reserved_stock',
    'wc_webhooks',
    'wc_product_download_directories',
    'wc_order_operational_data',
    'wc_order_addresses',
    'wc_orders_meta',
    'wc_orders',
];
